import React,{useState} from 'react';
import {Modal,QRCode,Select,Input,App as AntApp} from 'antd';
import {Copy,Download,ExternalLink} from 'lucide-react';
import {Action,useT,useAccount,copyText,settings,useAction} from './core';
export function Subscription({open,onClose}){
 const {subscribe}=useAccount(),t=useT(),{run}=useAction(),[types,setTypes]=useState(['auto']);
 let url=subscribe?.subscribe_url||'';try{const u=new URL(url);u.searchParams.set('types',types.includes('all')?'all':types.includes('auto')?'auto':types.join(','));url=u.href}catch{}
 const clients=[['Clash','clash://install-config?url='+encodeURIComponent(url)+'&name='+encodeURIComponent(settings.title||'')],['Hiddify','hiddify://import/'+encodeURIComponent(url)+'#'+encodeURIComponent(settings.title||'')],['Shadowrocket','sub://'+btoa(unescape(encodeURIComponent(url)))],['Stash','stash://install-config?url='+encodeURIComponent(url)],['Surge','surge:///install-config?url='+encodeURIComponent(url)],['Quantumult X','quantumult-x:///update-configuration?remote-resource='+encodeURIComponent(JSON.stringify({server_remote:[url+', tag='+settings.title]}))]];
 return <Modal title={t('一键订阅')} open={open} onCancel={onClose} footer={null} width={620} destroyOnHidden><div className="subscribe-dialog"><div className="qr-wrap"><QRCode value={url||'unavailable'} size={170}/><span>{t('扫描二维码订阅')}</span></div><div><label>{t('选择协议')}</label><Select mode="multiple" aria-label={t('选择协议')} value={types} onChange={v=>{const last=v.at(-1);setTypes(!v.length?['auto']:['auto','all'].includes(last)?[last]:v.filter(x=>!['auto','all'].includes(x)))}} options={['auto','all','anytls','vless','hysteria','hysteria2','shadowsocks','vmess','trojan'].map(v=>({value:v,label:v==='auto'?t('自动'):v==='all'?t('全部'):v}))}/><Input.TextArea readOnly value={url} aria-label={t('订阅地址')} autoSize={{minRows:2,maxRows:4}}/><Action onClick={()=>run(()=>copyText(url),t('复制成功'))}><Copy size={16}/>{t('复制订阅地址')}</Action></div></div><div className="client-grid">{clients.map(([name,link])=><a href={link} key={name}><Download size={15}/>{name}<ExternalLink size={13}/></a>)}</div><a className="quiet-link" href="#/knowledge" onClick={onClose}>{t('不会使用，查看使用教程')}</a></Modal>
}
